#pragma once

#define GSE_STACK_TOTAL 256
#define STEVE_STACK_TOTAL 512
#define COMMAND_STACK_TOTAL 1024
#define TELEMETRY_STACK_TOTAL 1024
#define RADIO_STACK_TOTAL 512
#define FILESYSTEM_STACK_TOTAL 1024
#define WATCHDOG_STACK_TOTAL 1024

int main();
